import type { NearbyService } from './types';

/**
 * Local dummy nearby services used until a live provider API is connected.
 * Distances and ETAs are static placeholders for UI development only.
 */
export const DUMMY_SERVICES: NearbyService[] = [
  {
    id: 'svc-1',
    name: 'Sharma Auto Care',
    category: 'Mechanic',
    icon: '🛠️',
    distanceKm: 1.8,
    rating: 4.8,
    etaMinutes: 12,
    status: 'Open',
    phoneNumber: '+919876543210',
  },
  {
    id: 'svc-2',
    name: 'Rapid Tow Express',
    category: 'Tow Truck',
    icon: '🚚',
    distanceKm: 3.2,
    rating: 4.6,
    etaMinutes: 18,
    status: 'Open',
    phoneNumber: '+919812345678',
  },
  {
    id: 'svc-3',
    name: 'FuelOnCall Delhi',
    category: 'Fuel Delivery',
    icon: '⛽',
    distanceKm: 2.4,
    rating: 4.5,
    etaMinutes: 20,
    status: 'Open',
    phoneNumber: '+919900112233',
  },
  {
    id: 'svc-4',
    name: 'ChargeHub Station',
    category: 'EV Charging',
    icon: '🔋',
    distanceKm: 4.1,
    rating: 4.7,
    etaMinutes: 15,
    status: 'Open',
    phoneNumber: '+919955667788',
  },
  {
    id: 'svc-5',
    name: 'JumpStart Pros',
    category: 'Battery Jump',
    icon: '⚡',
    distanceKm: 2.9,
    rating: 4.4,
    etaMinutes: 16,
    status: 'Closed',
    phoneNumber: '+919944556677',
  },
  {
    id: 'svc-6',
    name: 'TyreFix Mobile Unit',
    category: 'Flat Tyre',
    icon: '🛞',
    distanceKm: 1.2,
    rating: 4.9,
    etaMinutes: 10,
    status: 'Open',
    phoneNumber: '+919933221100',
  },
  {
    id: 'svc-7',
    name: 'Metro Garage Hub',
    category: 'Mechanic',
    icon: '🔧',
    distanceKm: 5.0,
    rating: 4.3,
    etaMinutes: 25,
    status: 'Open',
    phoneNumber: '+919911223344',
  },
  {
    id: 'svc-8',
    name: 'Night Rescue Tow',
    category: 'Tow Truck',
    icon: '🚛',
    distanceKm: 6.3,
    rating: 4.2,
    etaMinutes: 30,
    status: 'Closed',
    phoneNumber: '+919966778899',
  },
  {
    id: 'svc-9',
    name: 'PowerBoost Assist',
    category: 'Battery Jump',
    icon: '🔌',
    distanceKm: 3.5,
    rating: 4.6,
    etaMinutes: 14,
    status: 'Open',
    phoneNumber: '+919900334455',
  },
];
